# .goreleaser.yml
project_name: pastectl
version: 2

before:
  hooks:
    - go mod tidy

builds:
  -
    main: .
    binary: pastectl
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

archives:
  -
    files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

# no brews, no scoops

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'Merge pull request'

release:
  draft: false
  prerelease: auto
